# Collaborative Workflow Configuration
# This configuration defines a workflow where multiple expert models interact together

name: collaborative
description: A collaborative workflow where different expert models interact to analyze requirements, design, implement and review code

stages:
  - name: requirements_analysis
    type: collaborative
    description: Analyze and clarify requirements through a collaborative conversation
    participants:
      - role: requirements_analysis
        primary_model: deepseek/deepseek-chat-v3-0324:free
      - role: domain_expert
        primary_model: meta-llama/llama-4-maverick:free
      - role: user_advocate
        primary_model: google/gemini-2.5-pro-exp-03-25:free
    validation:
      required_sections:
        - Problem Statement
        - Functional Requirements
        - Non-Functional Requirements
        - User Stories
        - Constraints
        - Assumptions
      retry_on_failure: true
      max_retries: 2

  - name: system_design
    type: collaborative
    description: Design the system architecture through a collaborative conversation
    participants:
      - role: system_design
      - role: security_expert
      - role: performance_engineer
    validation:
      required_sections:
        - Architecture Overview
        - Component Design
        - Data Model
        - API Design
        - Security Considerations
        - Performance Considerations
      retry_on_failure: true
      max_retries: 2

  - name: implementation_planning
    type: collaborative
    description: Plan the implementation through a collaborative conversation
    participants:
      - role: technical_lead
      - role: developer
      - role: qa_engineer
    validation:
      required_sections:
        - Implementation Strategy
        - Task Breakdown
        - Dependencies
        - Timeline
        - Testing Strategy
        - Risks and Mitigations
      retry_on_failure: true
      max_retries: 2

  - name: code_generation
    type: collaborative
    description: Generate code through a collaborative conversation
    participants:
      - role: senior_developer
      - role: code_review
      - role: technical_writer
    validation:
      required_sections:
        - Code Implementation
        - Unit Tests
        - Documentation
        - Usage Examples
      retry_on_failure: true
      max_retries: 2

  - name: code_review
    type: collaborative
    description: Review and improve the generated code through a collaborative conversation
    participants:
      - role: code_review
      - role: security_auditor
      - role: performance_analyst
    validation:
      required_sections:
        - Code Quality Assessment
        - Security Analysis
        - Performance Analysis
        - Improvement Recommendations
        - Final Verdict
      retry_on_failure: true
      max_retries: 2