# Collaborative Workflow Configuration
# This configuration matches the expected format for the collaborative task orchestrator

name: metagpt_workflow
description: A collaborative workflow where different expert models interact to analyze requirements, design, and implement code

stages:
  - name: requirements_analysis
    type: collaborative
    description: Analyze and clarify requirements through a collaborative conversation
    participants:
      - role: requirements_analysis
        primary_model: deepseek/deepseek-chat-v3-0324:free
      - role: domain_expert
        primary_model: deepseek/deepseek-chat-v3-0324:free
      - role: user_advocate
        primary_model: deepseek/deepseek-chat-v3-0324:free

  - name: system_design
    type: collaborative
    description: Design the system architecture through a collaborative conversation
    participants:
      - role: architect
        primary_model: deepseek/deepseek-chat-v3-0324:free
      - role: developer
        primary_model: deepseek/deepseek-chat-v3-0324:free
      - role: security_expert
        primary_model: deepseek/deepseek-chat-v3-0324:free

  - name: implementation_planning
    type: collaborative
    description: Plan the implementation through a collaborative conversation
    participants:
      - role: project_manager
        primary_model: deepseek/deepseek-chat-v3-0324:free
      - role: developer
        primary_model: deepseek/deepseek-chat-v3-0324:free
      - role: qa_engineer
        primary_model: deepseek/deepseek-chat-v3-0324:free
